version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: strapi_db
      MYSQL_USER: strapi_user
      MYSQL_PASSWORD: strapipassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  strapi:
    image: strapi/strapi:latest
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql_db
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapipassword
      JWT_SECRET: yourRandomJwtSecret
      ADMIN_JWT_SECRET: yourRandomAdminJwtSecret
      APP_KEYS: yourAppKey1,yourAppKey2
      NODE_ENV: development
    volumes:
      - ./backend:/srv/app
      - strapi_uploads:/srv/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - mysql_db
    restart: unless-stopped
    # command: strapi develop # Uncomment if necessary

volumes:
  mysql_data:
  strapi_uploads:
